### Data cleaning and Transformation in python pandas

In [14]:
#import necessary library
import pandas as pd
import json

In [15]:
match_data= pd.read_csv("match_data.csv")

In [16]:
match_data.shape

(45, 7)

In [17]:
match_data.rename({'scorecard':'matchID'}, axis=1, inplace=True)
match_data.head()

,team1,team2,winner,margin,ground,matchDate,matchID
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [18]:
matchID_dict={}

for index, row in match_data.iterrows():
    key1=row['team1'] + ' Vs ' + row['team2']
    key2=row['team2'] + ' Vs ' + row['team1']
    
    matchID_dict[key1] = row['matchID']
    matchID_dict[key2] = row['matchID']
    
matchID_dict

{'Namibia Vs Sri Lanka': 'T20I # 1823',
 'Sri Lanka Vs Namibia': 'T20I # 1823',
 'Netherlands Vs U.A.E.': 'T20I # 1825',
 'U.A.E. Vs Netherlands': 'T20I # 1825',
 'Scotland Vs West Indies': 'T20I # 1826',
 'West Indies Vs Scotland': 'T20I # 1826',
 'Ireland Vs Zimbabwe': 'T20I # 1828',
 'Zimbabwe Vs Ireland': 'T20I # 1828',
 'Namibia Vs Netherlands': 'T20I # 1830',
 'Netherlands Vs Namibia': 'T20I # 1830',
 'Sri Lanka Vs U.A.E.': 'T20I # 1832',
 'U.A.E. Vs Sri Lanka': 'T20I # 1832',
 'Ireland Vs Scotland': 'T20I # 1833',
 'Scotland Vs Ireland': 'T20I # 1833',
 'West Indies Vs Zimbabwe': 'T20I # 1834',
 'Zimbabwe Vs West Indies': 'T20I # 1834',
 'Netherlands Vs Sri Lanka': 'T20I # 1835',
 'Sri Lanka Vs Netherlands': 'T20I # 1835',
 'Namibia Vs U.A.E.': 'T20I # 1836',
 'U.A.E. Vs Namibia': 'T20I # 1836',
 'Ireland Vs West Indies': 'T20I # 1837',
 'West Indies Vs Ireland': 'T20I # 1837',
 'Scotland Vs Zimbabwe': 'T20I # 1838',
 'Zimbabwe Vs Scotland': 'T20I # 1838',
 'Australia Vs New Zealand': 'T20I # 1839',
 'New Zealand Vs Australia': 'T20I # 1839',
 'Afghanistan Vs England': 'T20I # 1840',
 'England Vs Afghanistan': 'T20I # 1840',
 'Ireland Vs Sri Lanka': 'T20I # 1841',
 'Sri Lanka Vs Ireland': 'T20I # 1841',
 'India Vs Pakistan': 'T20I # 1842',
 'Pakistan Vs India': 'T20I # 1842',
 'Bangladesh Vs Netherlands': 'T20I # 1843',
 'Netherlands Vs Bangladesh': 'T20I # 1843',
 'South Africa Vs Zimbabwe': 'T20I # 1844',
 'Zimbabwe Vs South Africa': 'T20I # 1844',
 'Australia Vs Sri Lanka': 'T20I # 1845',
 'Sri Lanka Vs Australia': 'T20I # 1845',
 'England Vs Ireland': 'T20I # 1846',
 'Ireland Vs England': 'T20I # 1846',
 'Afghanistan Vs New Zealand': 'T20I # 1846a',
 'New Zealand Vs Afghanistan': 'T20I # 1846a',
 'Bangladesh Vs South Africa': 'T20I # 1847',
 'South Africa Vs Bangladesh': 'T20I # 1847',
 'India Vs Netherlands': 'T20I # 1848',
 'Netherlands Vs India': 'T20I # 1848',
 'Pakistan Vs Zimbabwe': 'T20I # 1849',
 'Zimbabwe Vs Pakistan': 'T20I # 1849',
 'Afghanistan Vs Ireland': 'T20I # 1849a',
 'Ireland Vs Afghanistan': 'T20I # 1849a',
 'Australia Vs England': 'T20I # 1849b',
 'England Vs Australia': 'T20I # 1849b',
 'New Zealand Vs Sri Lanka': 'T20I # 1850',
 'Sri Lanka Vs New Zealand': 'T20I # 1850',
 'Bangladesh Vs Zimbabwe': 'T20I # 1851',
 'Zimbabwe Vs Bangladesh': 'T20I # 1851',
 'Netherlands Vs Pakistan': 'T20I # 1852',
 'Pakistan Vs Netherlands': 'T20I # 1852',
 'India Vs South Africa': 'T20I # 1853',
 'South Africa Vs India': 'T20I # 1853',
 'Australia Vs Ireland': 'T20I # 1855',
 'Ireland Vs Australia': 'T20I # 1855',
 'Afghanistan Vs Sri Lanka': 'T20I # 1856',
 'Sri Lanka Vs Afghanistan': 'T20I # 1856',
 'England Vs New Zealand': 'T20I # 1858',
 'New Zealand Vs England': 'T20I # 1858',
 'Netherlands Vs Zimbabwe': 'T20I # 1859',
 'Zimbabwe Vs Netherlands': 'T20I # 1859',
 'Bangladesh Vs India': 'T20I # 1860',
 'India Vs Bangladesh': 'T20I # 1860',
 'Pakistan Vs South Africa': 'T20I # 1861',
 'South Africa Vs Pakistan': 'T20I # 1861',
 'Ireland Vs New Zealand': 'T20I # 1862',
 'New Zealand Vs Ireland': 'T20I # 1862',
 'Australia Vs Afghanistan': 'T20I # 1864',
 'Afghanistan Vs Australia': 'T20I # 1864',
 'England Vs Sri Lanka': 'T20I # 1867',
 'Sri Lanka Vs England': 'T20I # 1867',
 'Netherlands Vs South Africa': 'T20I # 1871',
 'South Africa Vs Netherlands': 'T20I # 1871',
 'Bangladesh Vs Pakistan': 'T20I # 1872',
 'Pakistan Vs Bangladesh': 'T20I # 1872',
 'India Vs Zimbabwe': 'T20I # 1873',
 'Zimbabwe Vs India': 'T20I # 1873',
 'New Zealand Vs Pakistan': 'T20I # 1877',
 'Pakistan Vs New Zealand': 'T20I # 1877',
 'England Vs India': 'T20I # 1878',
 'India Vs England': 'T20I # 1878',
 'England Vs Pakistan': 'T20I # 1879',
 'Pakistan Vs England': 'T20I # 1879'}

**Batting summary**

In [24]:
batting_data= pd.read_csv("batting_summary.csv")

In [28]:
batting_data.head()

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,Out/Not_Out,matchID
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,Out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,Out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,Out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,Out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,Out,T20I # 1823

In [29]:
batting_data.info

<bound method DataFrame.info of                     match teamInnings  battingPos             batsmanName  \
0    Namibia Vs Sri Lanka     Namibia           1      Michael van Lingen
1    Namibia Vs Sri Lanka     Namibia           2           Divan la Cock
2    Namibia Vs Sri Lanka     Namibia           3  Jan Nicol Loftie-Eaton
3    Namibia Vs Sri Lanka     Namibia           4           Stephan Baard
4    Namibia Vs Sri Lanka     Namibia           5      Gerhard Erasmus(c)
..                    ...         ...         ...                     ...
694   Pakistan Vs England     England           3               Phil Salt
695   Pakistan Vs England     England           4              Ben Stokes
696   Pakistan Vs England     England           5             Harry Brook
697   Pakistan Vs England     England           6               Moeen Ali
698   Pakistan Vs England     England           7        Liam Livingstone

     runs  balls  4s  6s      SR Out/Not_Out      matchID
0       3      6   0   0   50.00         Out  T20I # 1823
1       9      9   1   0  100.00         Out  T20I # 1823
2      20     12   1   2  166.66         Out  T20I # 1823
3      26     24   2   0  108.33         Out  T20I # 1823
4      20     24   0   0   83.33         Out  T20I # 1823
..    ...    ...  ..  ..     ...         ...          ...
694    10      9   2   0  111.11         Out  T20I # 1879
695    52     49   5   1  106.12     Not_Out  T20I # 1879
696    20     23   1   0   86.95         Out  T20I # 1879
697    19     13   3   0  146.15         Out  T20I # 1879
698     1      1   0   0  100.00     Not_Out  T20I # 1879

[699 rows x 11 columns]>

In [26]:
batting_data.shape

(699, 11)

**Bowling Summary**

In [20]:
with open('t20_wc_bowling_summary.json') as f:
    data=json.load(f)
    
    all_records=[]
    for rec in data:
        all_records.extend(rec['bowlingSummary'])
all_records[:2]

[{'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Maheesh Theekshana',
  'overs': '4',
  'maiden': '0',
  'runs': '23',
  'wickets': '1',
  'economy': '5.75',
  '0s': '7',
  '4s': '0',
  '6s': '0',
  'wides': '2',
  'noBalls': '0'},
 {'match': 'Namibia Vs Sri Lanka',
  'bowlingTeam': 'Sri Lanka',
  'bowlerName': 'Dushmantha Chameera',
  'overs': '4',
  'maiden': '0',
  'runs': '39',
  'wickets': '1',
  'economy': '9.75',
  '0s': '6',
  '4s': '3',
  '6s': '1',
  'wides': '2',
  'noBalls': '0'}]

In [30]:
bowling_data=pd.read_csv('bowling_summary.csv')

In [32]:
bowling_data.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,matchID
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4.0,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4.0,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4.0,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4.0,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4.0,0,27,1,6.75,8,1,1,0,0,T20I # 1823

**Player Information**

In [33]:
players_data=pd.read_csv("players_information_with_image.csv")

In [34]:
players_data.head()

,name,team,image,battingStyle,bowlingStyle,playingRole,description
0,Najmul Hossain Shanto,Bangladesh,NaN,Left hand Bat,Right arm Offbreak,Top order Batter,Nazmul Hossain Shanto emerged from an unusual ...
1,Soumya Sarkar,Bangladesh,NaN,Left hand Bat,Right arm Medium fast,Middle order Batter,"A rarity among Bangladesh allrounders, top-ord..."
2,Litton Das,Bangladesh,NaN,Right hand Bat,NaN,Wicketkeeper Batter,Liton Das is the first wicketkeeper-batsman in...
3,Shakib Al Hasan(c),Bangladesh,NaN,Left hand Bat,Slow Left arm Orthodox,Allrounder,When the annals of Bangladesh cricket are sift...
4,Afif Hossain,Bangladesh,NaN,Left hand Bat,Right arm Offbreak,Allrounder,Bangladesh left-hander Afif Hossain made his T...

**cleanup weired characters**

In [35]:
players_data['name']=players_data['name'].apply(lambda x: x.replace('â€',''))
players_data['name']=players_data['name'].apply(lambda x: x.replace('\xa0',''))
players_data.head(10)

,name,team,image,battingStyle,bowlingStyle,playingRole,description
0,Najmul Hossain Shanto,Bangladesh,NaN,Left hand Bat,Right arm Offbreak,Top order Batter,Nazmul Hossain Shanto emerged from an unusual ...
1,Soumya Sarkar,Bangladesh,NaN,Left hand Bat,Right arm Medium fast,Middle order Batter,"A rarity among Bangladesh allrounders, top-ord..."
2,Litton Das,Bangladesh,NaN,Right hand Bat,NaN,Wicketkeeper Batter,Liton Das is the first wicketkeeper-batsman in...
3,Shakib Al Hasan(c),Bangladesh,NaN,Left hand Bat,Slow Left arm Orthodox,Allrounder,When the annals of Bangladesh cricket are sift...
4,Afif Hossain,Bangladesh,NaN,Left hand Bat,Right arm Offbreak,Allrounder,Bangladesh left-hander Afif Hossain made his T...
5,Mosaddek Hossain,Bangladesh,NaN,Right hand Bat,Right arm Offbreak,Middle order Batter,"Mosaddek Hossain, who comes from a family of c..."
6,Nurul Hasan,Bangladesh,NaN,Right hand Bat,NaN,Wicketkeeper Batter,"Nurul Hasan, who made his first-class debut in..."
7,Yasir Ali,Bangladesh,NaN,Right hand Bat,Right arm Offbreak,Middle order Batter,NaN
8,Wessly Madhevere,Zimbabwe,NaN,Right hand Bat,Right arm Offbreak,Allrounder,NaN
9,Craig Ervine(c),Zimbabwe,NaN,Left hand Bat,Right arm Offbreak,Middle order Batter,Few people in Zimbabwe cricket circles were su...

In [36]:
players_data[players_data['team']=='India']

,name,team,image,battingStyle,bowlingStyle,playingRole,description
178,KL Rahul,India,NaN,Right hand Bat,NaN,Opening Batter,"A tall, elegant right-hand batsman who can kee..."
179,Rohit Sharma(c),India,NaN,Right hand Bat,Right arm Offbreak,Top order Batter,"Languid and easy on the eye, Rohit Sharma owne..."
180,Virat Kohli,India,"https://img1.hscicdn.com/image/upload/f_auto,t...",Right hand Bat,Right arm Medium,Top order Batter,India has given to the world many a great cric...
181,Suryakumar Yadav,India,"https://img1.hscicdn.com/image/upload/f_auto,t...",Right hand Bat,"Right arm Medium, Right arm Offbreak",Batter,Hard-hitting 360-degree batter Suryakumar Yada...
182,Axar Patel,India,NaN,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,Left-arm spinner Axar Patel has been increasin...
183,Hardik Pandya,India,NaN,Right hand Bat,Right arm Medium fast,Allrounder,Hardik Pandya swears by living life king size ...
184,Dinesh Karthik,India,NaN,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Not many would forget the sight of Dinesh Kart...
185,Ravichandran Ashwin,India,NaN,Right hand Bat,Right arm Offbreak,Bowling Allrounder,R Ashwin took the tricks and skills he learned...
186,Bhuvneshwar Kumar,India,NaN,Right hand Bat,Right arm Medium,Bowler,"At the time of his India debut in 2012, Bhuvne..."
187,Arshdeep Singh,India,NaN,Left hand Bat,Left arm Medium fast,Bowler,NaN
188,Mohammed Shami,India,NaN,Right hand Bat,Right arm Fast,Bowler,Mohammed Shami was India's leading fast bowler...
194,Rishabh Pant,India,NaN,Left hand Bat,NaN,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."
196,Deepak Hooda,India,NaN,Right hand Bat,Right arm Offbreak,Allrounder,"An allrounder who can bat in any position, Dee..."